url: '/'
baseurl: '/'

title: 'Chris Hadfield'
subtitle: 'Multidisciplinary Designer and Developer'

collections:
  projects:
    output: true
    permalink: /projects/:name/

postcss:
  cache: false
  config: postcss.config.js

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
